version: '3.4'

networks:
  backend:

volumes:
  keycloak-database:

services:
  ocelotapigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: APIgateways/OcelotAPIGateway/Dockerfile
    ports:
    - 5100:80
    networks:
    - backend

  reviewservice:
    image: ${DOCKER_REGISTRY-}reviewservice
    build:
      context: .
      dockerfile: backend/Microservices/Review/ReviewService/Dockerfile
    networks:
    - backend

  keycloak-instance:
    image: quay.io/keycloak/keycloak:18.0.2
    container_name: "keycloak-instance"
    #command: import --file=/tmp/import/freedomfi-realm.json
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_DB_URL=jdbc:postgresql://keycloak-database:5432/keycloak
      
    volumes:
      - ./backup:/tmp/import
    ports:
      - "2222:8080"
    networks:
      - backend
    depends_on:
      - keycloak-database

  keycloak-database:
    image: postgres:14.2
    container_name: "keycloak-database"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "2223:5432"
    networks:
      - backend
    volumes:
      - keycloak-database:/var/lib/postgresql/data
